//
//  PSConstant.h
//  plusSign
//
//  Created by Genki-Oki on 12/6/09.
//  Copyright 2009 Genki-Oki. All rights reserved.
//

//
#import "cocos2d.h"

typedef enum tMODES {
	CAKE=0,
	HAPPY=1,
	TOUGH=2
} tMODE;

Animation *shineLogo; //Este NO es el mejor sitio para esto...(TEST)
// CONFIG
#define PSCONFIG_URL_SCOREBOARD_SITE @"http://plussign.genki-oki.com/scoreboardhtml/scoreboard.php"//"http://plussign.genki-oki.com/scoreboard"
#define PSCONFIG_URL_SCOREBOARD_SUBMIT @"http://plussign.genki-oki.com/scoreboardhtml/insert.php"

#define PSCONFIG_URL_SCOREBOARD_SUBMIT_POSTVALUE_UDID @"iphoneudid"
#define PSCONFIG_URL_SCOREBOARD_SUBMIT_POSTVALUE_NAME @"nickname"
#define PSCONFIG_URL_SCOREBOARD_SUBMIT_POSTVALUE_MODE @"mode"
#define PSCONFIG_URL_SCOREBOARD_SUBMIT_POSTVALUE_SCORE @"points"
#define PSCONFIG_URL_SCOREBOARD_SUBMIT_POSTVALUE_PLUSSIGN @"plus"
#define PSCONFIG_URL_SCOREBOARD_SUBMIT_POSTVALUE_MINUSSIGN @"minus"
#define PSCONFIG_URL_SCOREBOARD_SUBMIT_POSTVALUE_TIMESSIGN @"times"
#define PSCONFIG_URL_SCOREBOARD_SUBMIT_POSTVALUE_DIVISIONSIGN @"division"

#define PSCONFIG_SOUND_VOLUME_BACKGROUND 0.2f
#define PSCONFIG_SOUND_VOLUME_EFFECTS 1.0f

#define PSCONFIG_BLOCK_INFLATION 1.25f

#define PSCONFIG_FONT_FAMILY @"Verdana"
#define PSCONFIG_FONT_SIZE_TUTORIAL 20

#define PSCONFIG_TALKING_SPEED 30//15
#define PSCONFIG_TALKING_DURATION(length) length/(PSCONFIG_TALKING_SPEED/(length>30?1:2))
#define PSCONFIG_TALKING_TIMES(duration, delay, frames) duration / (delay * frames)

//SCORE
#define PSCONFIG_GAMEPLAY_SCORE_VALUE_NORMALBLOCK 100
#define PSCONFIG_GAMEPLAY_SCORE_VALUE_LEAFBLOCK -100 //-PSCONFIG_GAMEPLAY_SCORE_VALUE_NORMALBLOCK/4
#define PSCONFIG_GAMEPLAY_SCORE_VALUE_STARBLOCK -200 // -PSCONFIG_GAMEPLAY_SCORE_VALUE_NORMALBLOCK/2

#define PSCONFIG_GAMEPLAY_SCORE_VALUE_BONUS 800
#define PSCONFIG_GAMEPLAY_SCORE_VALUE_SIGN -200

#define PSCONFIG_GAMEPLAY_MOVECYCLERATIO 5//15

#define PSCONFIG_GAMEPLAY_GOAL_CAKE PSCONFIG_GAMEPLAY_GOAL_CALCULATE(30)
#define PSCONFIG_GAMEPLAY_GOAL_HAPPY PSCONFIG_GAMEPLAY_GOAL_CALCULATE(40)
#define PSCONFIG_GAMEPLAY_GOAL_TOUGH PSCONFIG_GAMEPLAY_GOAL_CALCULATE(60) 

#define PSCONFIG_GAMEPLAY_BLOCKS_ROWS 31//11
#define PSCONFIG_GAMEPLAY_BLOCKS_COLS 5

#define PSCONFIG_GAMEPLAY_GOAL_CALCULATE(percentage) percentage * PSCONFIG_GAMEPLAY_BLOCKS_ROWS * PSCONFIG_GAMEPLAY_BLOCKS_COLS * PSCONFIG_GAMEPLAY_SCORE_VALUE_NORMALBLOCK / 100

#define MinToSeconds(minutes) minutes*60

#define PSCONFIG_GAMEPLAY_TIME_CAKE MinToSeconds(6)
#define PSCONFIG_GAMEPLAY_TIME_HAPPY MinToSeconds(5)
#define PSCONFIG_GAMEPLAY_TIME_TOUGH MinToSeconds(4)

#define PSCONFIG_TUTORIAL_TIMETOREAD 10 //seconds

// ******

//BEGIN-POPUP
#define CONSTANT_POPUP_GIVINGPUP_BOX @"givingup_box.png"
#define CONSTANT_POPUP_GIVINGPUP_BUTTON_NO @"no_btn.png"
#define CONSTANT_POPUP_GIVINGPUP_BUTTON_YES @"yeah_btn.png"

#define CONSTANT_POPUP_SCORE_SUBMITTED_BOX @"scoresubmit_box.png"
#define CONSTANT_POPUP_SCORE_SUBMITTED_OK @"ok_btn.png"

#define CONSTANT_POPUP_SCORE_FAILED_BOX @"scorefailed_box.png"
#define CONSTANT_POPUP_SCORE_FAILED_AWWWW @"awww_btn.png"

//END-POPUP

//BEGIN-ANIMATIONS
// EXPLOSION
#define CONSTANT_ANIMATION_EXPLOSION_1 @"explosion_1.png"
#define CONSTANT_ANIMATION_EXPLOSION_2 @"explosion_2.png"
#define CONSTANT_ANIMATION_EXPLOSION_3 @"explosion_3.png"
#define CONSTANT_ANIMATION_EXPLOSION_4 @"explosion_4.png"

// GABI HEAD
#define CONSTANT_ANIMATION_GABIHEAD_1 @"gabihead_1_an.png"
#define CONSTANT_ANIMATION_GABIHEAD_2 @"gabihead_2_an.png"
#define CONSTANT_ANIMATION_GABIHEAD_3 @"gabihead_3_an.png"

#define CONSTANT_ANIMATION_GABIHEAD_1_SMALL @"gabiheadsmall_1_an.png"
#define CONSTANT_ANIMATION_GABIHEAD_2_SMALL @"gabiheadsmall_2_an.png"
#define CONSTANT_ANIMATION_GABIHEAD_3_SMALL @"gabiheadsmall_3_an.png"

// GABRIEL
#define CONSTANT_ANIMATION_GABRIEL_1 @"gabriel_1_an.png"
#define CONSTANT_ANIMATION_GABRIEL_2 @"gabriel_2_an.png"
#define CONSTANT_ANIMATION_GABRIEL_3 @"gabriel_3_an.png"

// INTRO BACKGROUND
#define CONSTANT_ANIMATION_INTROBACKGROUND_1 @"background_an_1.png"
#define CONSTANT_ANIMATION_INTROBACKGROUND_2 @"background_an_2.png"
#define CONSTANT_ANIMATION_INTROBACKGROUND_3 @"background_an_3.png"

// PLUS SIGN LOGO

// END-ANIMATIONS

//BEGIN-BACKGROUNDS
#define CONSTANT_BACKGROUND_GAMEPLAY_AFRICA @"africa_background.jpg"
#define CONSTANT_BACKGROUND_GAMEPLAY_CITY @"city_background.jpg"
#define CONSTANT_BACKGROUND_GAMEPLAY_FOREST @"forest_background.jpg"
#define CONSTANT_BACKGROUND_GAMEPLAY_JUNGLE @"jungle_background.jpg"
#define CONSTANT_BACKGROUND_GAMEPLAY_SEA @"sea_background.jpg"
#define CONSTANT_BACKGROUND_GAMEPLAY_SKY @"sky_background.jpg"
#define CONSTANT_BACKGROUND_GAMEPLAY_SNOWFIELD @"snowfield_background.jpg"
#define CONSTANT_BACKGROUND_GAMEPLAY_SPACE @"space_background.jpg"
#define CONSTANT_BACKGROUND_GAMEPLAY_VOLCANO @"volcano_background.jpg"

#define CONSTANT_BACKGROUND_MENU @"menu_background.png"
#define CONSTANT_BACKGROUND_TUTORIAL @"tutorial_background.jpg"
//END-BACKGROUNDS

//BEGIN-BLOCKS
#define CONSTANT_BLOCKS_LEAF_1 @"leaf_1.png"
#define CONSTANT_BLOCKS_LEAF_2 @"leaf_2.png"
#define CONSTANT_BLOCKS_STAR_1 @"star_1.png"
#define CONSTANT_BLOCKS_STAR_2 @"star_2.png"
#define CONSTANT_BLOCKS_GREY_1 @"grey_1.png"
//END-BLOCKS

//BEGIN-BUTTONS
#define CONSTANT_BUTTONS_ALRIGHT @"alright_btn.png"
#define CONSTANT_BUTTONS_BACKTOMENU @"backtomenu_btn.png"
#define CONSTANT_BUTTONS_BASICTUTORIAL @"basictutorial_btn.png"
#define CONSTANT_BUTTONS_BLOCKSTUTORIAL @"blockstutorial_btn.png"
#define CONSTANT_BUTTONS_CAKEMODE @"cakemode_btn.png"
#define CONSTANT_BUTTONS_DIVISION @"division_btn.png"
#define CONSTANT_BUTTONS_DONE @"done_btn.png"
#define CONSTANT_BUTTONS_GIVEUP @"giveup_btn.png"
#define CONSTANT_BUTTONS_HAPPYMODE @"happymode_btn.png"
#define CONSTANT_BUTTONS_LETSPLAY_MENU @"letsplay_menu_btn.png"
#define CONSTANT_BUTTONS_MATHTUTORIAL @"mathtutorial_btn.png"
#define CONSTANT_BUTTONS_MENU @"menu_btn.png"
#define CONSTANT_BUTTONS_MINUS @"minus_btn.png"
#define CONSTANT_BUTTONS_NEXT @"next_btn.png"
#define CONSTANT_BUTTONS_NOWAY @"noway_btn.png"
#define CONSTANT_BUTTONS_PLUS @"plus_btn.png"
#define CONSTANT_BUTTONS_SCOREBOARD @"scoreboard_btn.png"
#define CONSTANT_BUTTONS_SCOREBOARD_MENU @"scoreboard_menu_btn.png"
#define CONSTANT_BUTTONS_SUBMITSCORE @"submitscore_btn.png"
#define CONSTANT_BUTTONS_TEACHME_MENU @"teachme_menu_btn.png"
#define CONSTANT_BUTTONS_TIMES @"times_btn.png"
#define CONSTANT_BUTTONS_TOUGHMODE @"toughmode_btn.png"
//END-BUTTONS

//BEGIN-GAME ELEMENTS
#define CONSTANT_GAMEELEMENTS_BLACKBOX_1 @"blackbox_1.png"
#define CONSTANT_GAMEELEMENTS_BLACKBOX_2 @"blackbox_2.png"
#define CONSTANT_GAMEELEMENTS_BLACKBOX_3 @"blackbox_3.png"
#define CONSTANT_GAMEELEMENTS_PSCHARSET @"PSCharset.png"
#define CONSTANT_GAMEELEMENTS_RIGHTS2009 @"rights2009.png"
#define CONSTANT_GAMEELEMENTS_WHITE_BAR @"white-bar.png"
#define CONSTANT_GAMEELEMENTS_WHITEBAR @"whitebar.png"
//END-GAME ELEMENTS

//BEGIN-GO INTRO
#define CONSTANT_GOINTRO_INTRO @"GO.m4v"
//END-GO INTRO

//BEGIN-MUSIC
#define CONSTANT_MUSIC_MAINMENU CONSTANT_SOUNDS_ASCENDING

#define CONSTANT_MUSIC_GAMEPLAY_AFRICA CONSTANT_SOUNDS_THE_COCO_RACE
#define CONSTANT_MUSIC_GAMEPLAY_CITY CONSTANT_SOUNDS_EVERYTHINGS_FINE
#define CONSTANT_MUSIC_GAMEPLAY_FOREST CONSTANT_SOUNDS_UNDER_THE_SURFACE
#define CONSTANT_MUSIC_GAMEPLAY_JUNGLE CONSTANT_SOUNDS_THE_COCO_RACE
#define CONSTANT_MUSIC_GAMEPLAY_SEA CONSTANT_SOUNDS_CRYSTALS
#define CONSTANT_MUSIC_GAMEPLAY_SKY CONSTANT_SOUNDS_EVERYTHINGS_FINE
#define CONSTANT_MUSIC_GAMEPLAY_SNOWFIELD CONSTANT_SOUNDS_CRYSTALS
#define CONSTANT_MUSIC_GAMEPLAY_SPACE CONSTANT_SOUNDS_PLANETARY_SPIRIT
#define CONSTANT_MUSIC_GAMEPLAY_VOLCANO CONSTANT_SOUNDS_UNDER_THE_SURFACE

//END-MUSIC

//BEGIN-SIGNS
#define CONSTANT_SIGNS_PLUS @"plus_sign.png"
#define CONSTANT_SIGNS_MINUS @"minus_sign.png"
#define CONSTANT_SIGNS_TIMES @"times_sign.png"
#define CONSTANT_SIGNS_DIVISION @"division_sign.png"
//END-SIGNS

//BEGIN-SOUNDS
#define CONSTANT_SOUNDS_ASCENDING @"ascending.caf"
#define CONSTANT_SOUNDS_CRYSTALS @"crystals.caf"
#define CONSTANT_SOUNDS_EVERYTHINGS_FINE @"everythings fine.caf"
#define CONSTANT_SOUNDS_EXPLOSION_SOUND @"explosion sound.caf"
#define CONSTANT_SOUNDS_LOGO_DROP_SOUND @"logo drop sound.caf"
#define CONSTANT_SOUNDS_PLANETARY_SPIRIT @"planetary Spirit.caf"
#define CONSTANT_SOUNDS_THE_COCO_RACE @"the coco race.caf"
#define CONSTANT_SOUNDS_UNDER_THE_SURFACE @"under the surface.caf"

#define CONSTANT_SOUNDS_NEWBUTTONSOUND_SOUND1 @"button sound 1.caf"
#define CONSTANT_SOUNDS_NEWBUTTONSOUND_SOUND2 @"button sound 2.caf"

#define CONSTANT_SOUNDS_BLIP @"blip 5.caf"
//END-SOUNDS

//BEGIN-TUTORIAL ELEMENTS
#define CONSTANT_TUTORIALELEMENTS_TESTPLUS @"2-2 plus.png"
#define CONSTANT_TUTORIALELEMENTS_TESTMINUS @"8-4 minus.png"
#define CONSTANT_TUTORIALELEMENTS_TESTTIMES @"2-2 times.png"
#define CONSTANT_TUTORIALELEMENTS_TESTDIVISION @"8-2 division.png"

#define CONSTANT_TUTORIALELEMENTS_CROSS @"cross.png"
#define CONSTANT_TUTORIALELEMENTS_FINGER @"finger.png"
#define CONSTANT_TUTORIALELEMENTS_SIGNS @"signs.png"
#define CONSTANT_TUTORIALELEMENTS_X @"x.png"

#define CONSTANT_TUTORIALELEMENTS_TUTORIAL_CUBES_1 @"tutorial_cubes_1.png"
#define CONSTANT_TUTORIALELEMENTS_TUTORIAL_CUBES_2 @"tutorial_cubes_2.png"
#define CONSTANT_TUTORIALELEMENTS_TUTORIAL_CUBES_3 @"tutorial_cubes_3.png"
#define CONSTANT_TUTORIALELEMENTS_TUTORIAL_CUBES_4 @"tutorial_cubes_4.png"
#define CONSTANT_TUTORIALELEMENTS_TUTORIAL_CUBES_5 @"tutorial_cubes_5.png"
#define CONSTANT_TUTORIALELEMENTS_TUTORIAL_CUBES_6 @"tutorial_cubes_6.png"
#define CONSTANT_TUTORIALELEMENTS_TUTORIAL_CUBES_7 @"tutorial_cubes_7.png"
#define CONSTANT_TUTORIALELEMENTS_TUTORIAL_CUBES_8 @"tutorial_cubes_8.png"
#define CONSTANT_TUTORIALELEMENTS_TUTORIAL_CUBES_9 @"tutorial_cubes_9.png"
#define CONSTANT_TUTORIALELEMENTS_TUTORIAL_CUBES_10 @"tutorial_cubes_10.png"

//END-TUTORIAL ELEMENTS

//BEGIN-VOICE
#define CONSTANT_VOICE_FINISHED @"finished!.caf"
#define CONSTANT_VOICE_GO @"go!.caf"
#define CONSTANT_VOICE_GREAT @"great!.caf"
#define CONSTANT_VOICE_PLAY @"play!.caf"
#define CONSTANT_VOICE_READY @"ready?.caf"
#define CONSTANT_VOICE_TOUGH @"tough.caf"
#define CONSTANT_VOICE_YOU_LOST @"you lost.caf"
#define CONSTANT_VOICE_TALKING @"gabi voice.caf"
//END-VOICE

//BEGIN-WORD BUBBLES
#define CONSTANT_WORDBUBBLES_WORDBUBBLE_1 @"wordbubble_1.png"
#define CONSTANT_WORDBUBBLES_WORDBUBBLE_2 @"wordbubble_2.png"
#define CONSTANT_WORDBUBBLES_WORDBUBBLE_3 @"wordbubble_3.png"
#define CONSTANT_WORDBUBBLES_WORDBUBBLE_4 @"wordbubble_4.png"

#define CONSTANT_WORDBUBBLES_FINISHED @"finished.png"
#define CONSTANT_WORDBUBBLES_GO @"go.png"
#define CONSTANT_WORDBUBBLES_GREAT @"great.png"
#define CONSTANT_WORDBUBBLES_PLAY @"play.png"
#define CONSTANT_WORDBUBBLES_READY @"ready.png"
#define CONSTANT_WORDBUBBLES_TOUGH @"tough.png"
#define CONSTANT_WORDBUBBLES_YOU_LOST @"youlost.png"

#define CONSTANT_WORDBUBBLES_NEWWORDBUBBLES_WHITEREADY @"ready_white.png"
#define CONSTANT_WORDBUBBLES_NEWWORDBUBBLES_WHITEGO @"go_white.png"
#define CONSTANT_WORDBUBBLES_NEWWORDBUBBLES_WHITEBLOCK @"block_white.png"

//END-WORD BUBBLES


